/***************************************************************************
 * Copyright (c) 2025-2026                                                 *
 *      Volnei Cervi Puttini.  All rights reserved.                        *
 *      <vcputtini@vcplinux.com.br>                                        *
 *                                                                         *
 * Redistribution and use in source and binary forms, with or without      *
 * modification, are permitted provided that the following conditions      *
 * are met:                                                                *
 * 1. Redistributions of source code must retain the above copyright       *
 *    notice, this list of conditions and the following disclaimer.        *
 * 2. Redistributions in binary form must reproduce the above copyright    *
 *    notice, this list of conditions and the following disclaimer in the  *
 *    documentation and/or other materials provided with the distribution. *
 * 4. Neither the name of the Author     nor the names of its contributors *
 *    may be used to endorse or promote products derived from this software*
 *    without specific prior written permission.                           *
 *                                                                         *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND *
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE   *
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR      *
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS  *
 * BE LIABLEFOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR   *
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF    *
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS*
 * INTERRUPTION)                                                           *
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,     *
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING   *
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE      *
 * POSSIBILITY OFSUCH DAMAGE.                                              *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
#ifndef BORGINFOCOMMANDPARSER_H
#define BORGINFOCOMMANDPARSER_H

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QString>
#include <QStringList>
#include <QVariant>
#include <optional>

/*!
 * \brief Interprets and exposes the fields of the JSON generated by BorgBackup
 * (output of `borg info --json`).
 *
 * Quick usage:
 * \ccode
 * auto info = BorgInfoCommandParser::fromJson(rawJsonString);
 * if (info) {
 * qDebug() << info->archiveName();
 * qDebug() << info->repoLocation();
 * }
 * \endcode
 */
class BorgInfoCommandParser
{
public:
  /*!
   * \brief Constructs from a raw JSON string.
   * \return nullopt if the JSON is invalid.
   */
  [[nodiscard]] static std::optional<BorgInfoCommandParser> fromJson(
    const QString& json) noexcept;

  /*!
   * \brief Constructs from an already parsed QJsonDocument.
   * \return nullopt if the document is not an object.
   */
  [[nodiscard]] static std::optional<BorgInfoCommandParser> fromDocument(
    const QJsonDocument& doc) noexcept;

  // Archives

  /*! \brief Number of archives present in the JSON. */
  [[nodiscard]] int archiveCount() const noexcept;

  /*! \brief QJsonObject complete from archive at index @p idx. */
  [[nodiscard]] QJsonObject archive(int idx = 0) const noexcept;

  /*! \brief Archive name ("name" field). */
  [[nodiscard]] QString archiveName(int idx = 0) const noexcept;

  /*! \brief SHA-256 hash of the archive ("id" field). */
  [[nodiscard]] QString archiveId(int idx = 0) const noexcept;

  /*! \brief Hostname of the machine that generated the archive. */
  [[nodiscard]] QString archiveHostname(int idx = 0) const noexcept;

  /*! \brief User who executed borg. */
  [[nodiscard]] QString archiveUsername(int idx = 0) const noexcept;

  /*! \brief ISO-8601 timestamp of backup start. */
  [[nodiscard]] QString archiveStart(int idx = 0) const noexcept;

  /*! \brief ISO-8601 timestamp of backup end. */
  [[nodiscard]] QString archiveEnd(int idx = 0) const noexcept;

  /*! \brief Backup duration in seconds. */
  [[nodiscard]] double archiveDuration(int idx = 0) const noexcept;

  /*! \brief Comment associated with the archive. */
  [[nodiscard]] QString archiveComment(int idx = 0) const noexcept;

  /*! \brief Command line used to create the archive. */
  [[nodiscard]] QStringList archiveCommandLine(int idx = 0) const noexcept;

  /*! \brief Chunker parameters (algorithm + sizes). */
  [[nodiscard]] QVariantList archiveChunkerParams(int idx = 0) const noexcept;

  // Archive: stats

  /*! \brief Block "stats" do file as QJsonObject. */
  [[nodiscard]] QJsonObject archiveStats(int idx = 0) const noexcept;

  /*! \brief Size compressed in bytes. */
  [[nodiscard]] qint64 archiveCompressedSize(int idx = 0) const noexcept;

  /*! \brief Deduplicated size in bytes. */
  [[nodiscard]] qint64 archiveDedupSize(int idx = 0) const noexcept;

  /*! \brief Original size (before any compression) in bytes. */
  [[nodiscard]] qint64 archiveOriginalSize(int idx = 0) const noexcept;

  /*! \brief Number of files included do not archive. */
  [[nodiscard]] qint64 archiveFileCount(int idx = 0) const noexcept;

  // Archive: limits
  /*! \brief Maximum fraction of the repository that this file can occupy. */
  [[nodiscard]] double archiveMaxSize(int idx = 0) const noexcept;

  // Cache

  /*! \brief Path to the local cache of Borg. */
  [[nodiscard]] QString cachePath() const noexcept;

  /*! \brief Total non-cached chunks. */
  [[nodiscard]] qint64 cacheTotalChunks() const noexcept;

  /*! \brief Total number of unique non-cached chunks. */
  [[nodiscard]] qint64 cacheUniqueChunks() const noexcept;

  /*! \brief Total compressed cache size. */
  [[nodiscard]] qint64 cacheTotalCSize() const noexcept;

  /*! \brief Total size not compressed by cache. */
  [[nodiscard]] qint64 cacheTotalSize() const noexcept;

  /*! \brief Exclusive compressed size of two unique chunks. */
  [[nodiscard]] qint64 cacheUniqueCSize() const noexcept;

  /*! \brief Size does not compress two unique chunks. */
  [[nodiscard]] qint64 cacheUniqueSize() const noexcept;

  // Encryption
  /*! \brief Encryption mode ("none", "repokey", etc.). */
  [[nodiscard]] QString encryptionMode() const noexcept;

  // Repository

  /*! \brief ID (hash) of the repository. */
  [[nodiscard]] QString repoId() const noexcept;

  /*! \brief Timestamp ISO-8601 of the last modification of the repository. */
  [[nodiscard]] QString repoLastModified() const noexcept;

  /*! \brief Local path (or remote URL) to the repository. */
  [[nodiscard]] QString repoLocation() const noexcept;

  // Raw access

  /*! \brief Returns the root QJsonObject for free access. */
  [[nodiscard]] const QJsonObject& root() const noexcept { return m_root; }

private:
  explicit BorgInfoCommandParser(QJsonObject root) noexcept;

  // Safe navigation helpers
  [[nodiscard]] QJsonValue deepValue(
    const QJsonObject& obj,
    std::initializer_list<QString> path) const noexcept;
  [[nodiscard]] QJsonObject archiveObj(int idx) const noexcept;

  QJsonObject m_root;
  QJsonArray m_archives;
};

#endif // BORGINFOCOMMANDPARSER_H
